baseURL = "https://blog.namuori.net"
languageCode = "en-us"
title = "나무오리"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]

  author = "Kim Yu Seok"
  github = "NAMUORI00"
  Description = "I love github fork"

  headerIcon = "/images/github-mark.svg"
  avatar = "https://avatars.githubusercontent.com/u/46620366"

  [[params.links]]
    title = "Email"
    href = "mailto:admin@namuori.net"
    icon = "/images/email-icon.png"

  [[params.links]]
    title = "Website"
    href = "https://namuori.net"
    icon = "/images/website-icon.png"

# Sitemap Configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Hugo Mounts Configuration
[[module.mounts]]
source = "content/About-218dcd44779f81169bcedf9476baf73b.md"
target = "content/readme.md"

[[module.mounts]]
source = "content/posts"
target = "content/post"
