baseURL = "https://blog.namuori.net"
languageCode = "en-us"
title = "나무오리"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  headerIcon = "/images/github-icon.svg"
  avatar = "https://avatars.githubusercontent.com/u/46620366"
