baseURL = "https://blog.namuori.net"
languageCode = "en-us"
title = "나무오리"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]

  author = "Kim Yu Seok"
  github = "NAMUORI00"
  Description = "I love github fork"

  headerIcon = "/images/github-icon.svg"
  avatar = "https://avatars.githubusercontent.com/u/46620366"

  [[params.links]]
    title = "My-Organization"
    href = "https://github.com/my-org"
    icon = "https://via.placeholder.com/32" # 조직의 로고 이미지 URL

  [[params.links]]
    title = "Another-Org"
    href = "https://github.com/another-org"
    icon = "/images/another-org-icon.png" # static/images/ 에 위치한 아이콘
